### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by Cial39** [edgardmessias/glpi-singlesignon#32] opened 2022-06-29 19:01 UTC
The single sign on test is ok but error "PHP Notice: Array to string conversion in C:\inetpub\wwwroot\glpi\plugins\singlesignon\inc\toolbox.class.php on line 17" after disconnection. Can you help me.

**Comment by edgardmessias** [comment] 2022-06-29 19:08
Duplicate of #31

**Closed by edgardmessias** 2022-06-29 19:08 UTC
